#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v10
# autospec commit: 5905be9
#
Name     : R-fastmap
Version  : 1.2.0
Release  : 34
URL      : https://cran.r-project.org/src/contrib/fastmap_1.2.0.tar.gz
Source0  : https://cran.r-project.org/src/contrib/fastmap_1.2.0.tar.gz
Summary  : Fast Data Structures
Group    : Development/Tools
License  : MIT
Requires: R-fastmap-lib = %{version}-%{release}
Requires: R-fastmap-license = %{version}-%{release}
BuildRequires : buildreq-R

%description
store, stack, and queue. Environments are commonly used as key-value stores
    in R, but every time a new key is used, it is added to R's global symbol
    table, causing a small amount of memory leakage. This can be problematic in
    cases where many different keys are used. Fastmap avoids this memory leak
    issue by implementing the map using data structures in C++.

%package lib
Summary: lib components for the R-fastmap package.
Group: Libraries
Requires: R-fastmap-license = %{version}-%{release}

%description lib
lib components for the R-fastmap package.


%package license
Summary: license components for the R-fastmap package.
Group: Default

%description license
license components for the R-fastmap package.


%prep
%setup -q -n fastmap
pushd ..
cp -a fastmap buildavx2
popd
pushd ..
cp -a fastmap buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1715787367

%install
export SOURCE_DATE_EPOCH=1715787367
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/R-fastmap
cp %{_builddir}/fastmap/LICENSE.note %{buildroot}/usr/share/package-licenses/R-fastmap/15211d8f49cbae47a72108a4132b9ef272343557 || :
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/fastmap/DESCRIPTION
/usr/lib64/R/library/fastmap/INDEX
/usr/lib64/R/library/fastmap/LICENSE
/usr/lib64/R/library/fastmap/Meta/Rd.rds
/usr/lib64/R/library/fastmap/Meta/features.rds
/usr/lib64/R/library/fastmap/Meta/hsearch.rds
/usr/lib64/R/library/fastmap/Meta/links.rds
/usr/lib64/R/library/fastmap/Meta/nsInfo.rds
/usr/lib64/R/library/fastmap/Meta/package.rds
/usr/lib64/R/library/fastmap/NAMESPACE
/usr/lib64/R/library/fastmap/NEWS.md
/usr/lib64/R/library/fastmap/R/fastmap
/usr/lib64/R/library/fastmap/R/fastmap.rdb
/usr/lib64/R/library/fastmap/R/fastmap.rdx
/usr/lib64/R/library/fastmap/help/AnIndex
/usr/lib64/R/library/fastmap/help/aliases.rds
/usr/lib64/R/library/fastmap/help/fastmap.rdb
/usr/lib64/R/library/fastmap/help/fastmap.rdx
/usr/lib64/R/library/fastmap/help/paths.rds
/usr/lib64/R/library/fastmap/html/00Index.html
/usr/lib64/R/library/fastmap/html/R.css
/usr/lib64/R/library/fastmap/tests/testthat.R
/usr/lib64/R/library/fastmap/tests/testthat/helpers-fastmap.R
/usr/lib64/R/library/fastmap/tests/testthat/test-encoding.R
/usr/lib64/R/library/fastmap/tests/testthat/test-map.R
/usr/lib64/R/library/fastmap/tests/testthat/test-queue.R
/usr/lib64/R/library/fastmap/tests/testthat/test-serialize.R
/usr/lib64/R/library/fastmap/tests/testthat/test-shrink.R
/usr/lib64/R/library/fastmap/tests/testthat/test-stack.R

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/fastmap/libs/fastmap.so
/V4/usr/lib64/R/library/fastmap/libs/fastmap.so
/usr/lib64/R/library/fastmap/libs/fastmap.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/R-fastmap/15211d8f49cbae47a72108a4132b9ef272343557
